### ISSUE TITLE
react view( Type script 제외 ) 빌드

### ISSUE THREAD

**Issue by askePhoenix** [askePhoenix/Develop-side-site-view#1]
**[ 이슈 내용 ]**
1. 모든 내용을 지우고 빌드 되도록 수정함.
2. ~~이후 테스트 코드에 대한 코멘트 작성 후, 해당 코멘트를 진행함.~~
3. Circle Ci 세팅 추가

**[ 빌드 내용 ]**
- NodeJs yarn
- ~~TypeScript~~
- React

**[ 진행 사항 ]**
- [ ] ~~적용 및 push~~
- [x] 빌드
- [ ] ~~빌드 후, 코멘트 작성~~
- [x] Add Circle-Ci Setting

**Comment by askeundaia** [comment]
이슈 작업/적용 완료
